package by.victory.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ExportProdAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExportProdAllPropertiesEquals(ExportProd expected, ExportProd actual) {
        assertExportProdAutoGeneratedPropertiesEquals(expected, actual);
        assertExportProdAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExportProdAllUpdatablePropertiesEquals(ExportProd expected, ExportProd actual) {
        assertExportProdUpdatableFieldsEquals(expected, actual);
        assertExportProdUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExportProdAutoGeneratedPropertiesEquals(ExportProd expected, ExportProd actual) {
        assertThat(expected)
            .as("Verify ExportProd auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExportProdUpdatableFieldsEquals(ExportProd expected, ExportProd actual) {
        assertThat(expected)
            .as("Verify ExportProd relevant properties")
            .satisfies(e -> assertThat(e.getDepartureDate()).as("check departureDate").isEqualTo(actual.getDepartureDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExportProdUpdatableRelationshipsEquals(ExportProd expected, ExportProd actual) {
        assertThat(expected)
            .as("Verify ExportProd relationships")
            .satisfies(e -> assertThat(e.getTrip()).as("check trip").isEqualTo(actual.getTrip()))
            .satisfies(e -> assertThat(e.getGrade()).as("check grade").isEqualTo(actual.getGrade()));
    }
}
